version: "3"

services:
  r-proxy:
    image: nginx:alpine
    networks:
      app_net:
        ipv4_address: 172.16.238.10

  go:
    container_name: goAPIserver
    build: ./Go/
    tty: true
    environment:
      TZ: "Asia/Tokyo"
    volumes:
      - ./Go/app/:/app
    ports:
      - "8000:8000"
    networks:
      app_net:
        ipv4_address: 172.16.238.30

  node:
    build: ./node
    container_name: node
    tty: true
    volumes:
      - ./node/app/:/app
    ports:
      - "3000:3000"
    networks:
      app_net:
        ipv4_address: 172.16.238.20

  postgre:
    container_name: postgre
    build: ./DB/
    volumes:
      - ./DB/init/init.*:/docker-entrypoint-initdb.d/
    env_file: ./DB/.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.40

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24

volumes:
  data:
